[package]
name = "psh-tiny"
version = "0.1.0"
authors = ["Lucas Stil <lucas@platform.sh>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
base64 = "0.10"
clap = "2.33"
psh_config = { path = "psh_config" }
