[package]
name = "psh-tiny"
version = "0.1.0"
authors = ["Lucas Stil <lucas@platform.sh>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
base64 = "0.10"
clap = "2.33"
psh_config = { git = "ssh://git@github.com/Oc7at/psh_config.git", ref = "3a74e45" }
